#!/usr/bin/env bash
# ============================================================
# REALITY FX — ONE-COMMAND LIVE DEPLOY
# ------------------------------------------------------------
#   perl audit-regression.pl   -> structural gate (abort on findings)
#   stage the OS app at root   -> index.html + css/ + js/ + _redirects + netlify/
#   deploy-flow.pl             -> Netlify REST pipeline (content-addressed, only
#                                 changed files upload, polls to ready)
#   verify                     -> live stamp + /api rails answer
#
# Usage:  bash deploy-live.sh
# Env:    NETLIFY_TOKEN / NETLIFY_SITE_ID can override the defaults below.
# ============================================================

set -euo pipefail
cd "$(dirname "$0")"

TOKEN="${NETLIFY_TOKEN:-$(cat .freebuff/tools/netlify-token.txt 2>/dev/null || true)}"
SITE_ID="${NETLIFY_SITE_ID:-3c3b9935-9865-47dc-9db0-80de5f8e4591}"   # reality-fx-os
STAGE="$(pwd)/.freebuff/tools/deploy-stage"   # absolute — File::Find chdirs during hashing

[ -n "$TOKEN" ] || { echo "✗ no NETLIFY_TOKEN (set it or fill .freebuff/tools/netlify-token.txt)"; exit 1; }

echo "════════════════════════════════════════════"
echo "  REALITY FX — LIVE DEPLOY"
echo "  $(date)"
echo "════════════════════════════════════════════"

# 0) credit pre-flight — report what the account says, then probe the real gate.
# The account object's counters can lag reality (the API showed 0 used while
# deploys were blocked), so we ALSO fire the deploy-create call: it either
# creates the deploy (proceed) or returns the credit verdict immediately.
echo ""
echo "[0/5] Netlify credit check"
ACCT_JSON=$(curl -s "https://api.netlify.com/api/v1/accounts/6a7a49f0e7c10e74a063c61c?access_token=$TOKEN" 2>/dev/null || echo "{}")
PLAN=$(echo "$ACCT_JSON" | grep -oE '"plan_credits"\s*:\s*[0-9.]+' | grep -oE '[0-9.]+' | head -1)
USED=$(echo "$ACCT_JSON" | grep -oE '"credits"\s*:\s*\{"included"\s*:\s*[0-9.]+,\s*"used"\s*:\s*[0-9.]+' | grep -oE '"used"\s*:\s*[0-9.]+' | grep -oE '[0-9.]+' | head -1)
TOPUP=$(echo "$ACCT_JSON" | grep -oE '"swar_auto_topup_credits"\s*:\s*[0-9.]+' | grep -oE '[0-9.]+' | head -1)
echo "  account says: plan $PLAN credits/month, used $USED this period, auto-topup $TOPUP"
CREATE=$(curl -s -X POST "https://api.netlify.com/api/v1/sites/$SITE_ID/deploys?access_token=$TOKEN" -H "Content-Type: application/json" -d '{"draft":false}')
if echo "$CREATE" | grep -q '"id"'; then
  echo "  gate: OPEN — a deploy can be created ("$(echo "$CREATE" | grep -oE '"state"\s*:\s*"[a-z]+' | grep -oE '[a-z]+' | head -1)")"
elif echo "$CREATE" | grep -qi 'credit'; then
  echo "  ✗ gate: CLOSED — Netlify says: $(echo "$CREATE" | grep -oE '"error"\s*:\s*"[^"]*' | sed 's/"error"\s*:\s*"//' | head -1)"
  echo "  ✗ Nothing was deployed. Add credits or wait for the monthly cycle, then rerun."
  exit 1
else
  echo "  ⚠ gate: UNKNOWN — $(echo "$CREATE" | head -c 120)"
  echo "  (continuing — the pipeline's own create call will give the final verdict)"
fi

# 1) the gate — the machine walks the building first
echo ""
echo "[1/5] Regression audit"
if ! perl audit-regression.pl; then
  echo "✗ AUDIT FAILED — fix the findings above before going live. Nothing was deployed."
  exit 1
fi

# 2) stage the OS app at the site root (+ API rail + functions)
echo ""
echo "[2/4] Staging the OS app at site root"
rm -rf "$STAGE" && mkdir -p "$STAGE"
cp -r REALITY-FOREX-TRADING-/os/index.html "$STAGE/"
cp -r REALITY-FOREX-TRADING-/os/css   "$STAGE/"
cp -r REALITY-FOREX-TRADING-/os/js    "$STAGE/"
cp _redirects "$STAGE/_redirects"
# the PWA layer (manifest, service worker, install guide) rides every deploy,
# and its _headers grants the worker site-wide scope (Service-Worker-Allowed: /)
cp -r rfx-pwa "$STAGE/rfx-pwa"
cp rfx-pwa/_headers "$STAGE/_headers"
mkdir -p "$STAGE/netlify/functions"
cp netlify/functions/osapi.js   "$STAGE/netlify/functions/"
cp netlify/functions/envprobe.js "$STAGE/netlify/functions/"
# deploy-baked secrets (free-plan env fallback): Netlify's env-var create API
# needs a paid account, so the mail rail's vars ride the deploy in a generated
# module. Source file is .freebuff/tools/secrets.env — never committed, never
# uploaded as a static file (it lives outside $STAGE). UI-set env vars win at
# runtime because osapi.js checks process.env first.
if [ -f .freebuff/tools/secrets.env ]; then
  {
    echo '"use strict";'
    echo '/* generated by deploy-live.sh from .freebuff/tools/secrets.env — never commit the source file */'
    echo 'module.exports = {'
    sed -n 's/^\([A-Z0-9_]*\)=\(.*\)$/  \1: "\2",/p' .freebuff/tools/secrets.env
    echo '};'
  } > "$STAGE/netlify/functions/rfx-env.js"
  echo "  baked $(grep -c ':' "$STAGE/netlify/functions/rfx-env.js") mail secret(s) into the function bundle"
else
  echo "  (no .freebuff/tools/secrets.env — mail rail stays in demo mode)"
fi
echo "  staged $(find "$STAGE" -type f | wc -l) files, stamp: $(grep -oE 'v=[0-9]+' "$STAGE/index.html" | sort -u)"

# 3) push through the tested REST pipeline
echo ""
echo "[3/4] Pushing to Netlify (only changed files upload)"
DEPLOY_DIR="$STAGE" NETLIFY_TOKEN="$TOKEN" NETLIFY_SITE_ID="$SITE_ID" perl .freebuff/tools/deploy-flow.pl
echo "  deploy pipeline finished"

# 4) verify the live site actually serves the new build
echo ""
echo "[4/4] Verifying the live site"
LIVE="https://reality-fx-os.netlify.app"
STAMP=$(curl -s "$LIVE/" | grep -oE 'v=[0-9]+' | sort -u | tr '\n' ' ')
echo "  live stamp:  $STAMP"
curl -s -o /dev/null -w "  /               → %{http_code}\n" "$LIVE/"
curl -s -o /dev/null -w "  /os/api/handoffs → %{http_code}\n" "$LIVE/os/api/handoffs"
curl -s -o /dev/null -w "  /api/flags       → %{http_code}\n" "$LIVE/api/flags"
echo ""
echo "✅ DONE — one command, whole building walked, live site updated."
